import './styles.css';
import './compact-scoreboard.css';
import './compact-header.css';
import './player-board-copy.css';
import './team-logos.css';
import './signal-palette.css';
import './objective-icons.css';
import './arena-brand.css';
import './lane-gold-polish.css';
import './loading-states.css';
import { startWebV2 } from './app.ts';
import { installArenaBrand } from './arena-brand.ts';
import { installCatalogueFinality } from './catalogue-finality.ts';
import { installCatalogueTeamLogos } from './catalogue-team-logos.ts';
import { installChampionPortraitAssets } from './champion-portrait-assets.ts';
import { installCompactHeader } from './compact-header.ts';
import { installLiveLifecycle } from './live-lifecycle.ts';
import { installLoadingStates } from './loading-states.ts';
import { installPlayerBoardCopy } from './player-board-copy.ts';
import { installTeamSideIdentity } from './team-side-identity.ts';
import { installWinnerDeclaration } from './winner-declaration.ts';

const root = document.querySelector<HTMLElement>('#app');
if (!root) throw new Error('Missing #app root.');

installCatalogueFinality();
installLiveLifecycle(root);
installCatalogueTeamLogos(root);
installPlayerBoardCopy(root);
startWebV2(root);
installLoadingStates(root);
installArenaBrand(root);
installChampionPortraitAssets(root);
installTeamSideIdentity(root);
installWinnerDeclaration(root);
installCompactHeader(root);
