import './styles.css';
import './compact-scoreboard.css';
import './compact-header.css';
import './player-board-copy.css';
import './team-logos.css';
import './signal-palette.css';
import './objective-icons.css';
import './grubs-objective.css';
import './arena-brand.css';
import './lane-gold-polish.css';
import './scoreboard-scale.css';
import './scoreboard-polish.css';
import './loading-states.css';
import './major-league-filter.css';
import './homepage-dashboard.css';
import './experience-polish.css';
import './match-experience-refine.css';
import './dota-livescore.css';
import './pwa.css';
import './native-insets.css';
import './app-updater.css';
import { startWebV2 } from './app.ts';
import { installApiReliability } from './api-reliability.ts';
import { installArenaBrand } from './arena-brand.ts';
import { installCatalogueExperience } from './catalogue-experience.ts';
import { installCatalogueFinality } from './catalogue-finality.ts';
import { installCatalogueSeriesScores } from './catalogue-series-scores.ts';
import { installCatalogueTeamLogos } from './catalogue-team-logos.ts';
import { installChampionPortraitAssets } from './champion-portrait-assets.ts';
import { installDataStatus } from './data-status.ts';
import { installFinalSeriesTabs } from './final-series-tabs.ts';
import { installFinalSnapshotPolling } from './final-snapshot-polling.ts';
import { installGrubsObjective } from './grubs-objective.ts';
import { installHomeDashboard } from './home-dashboard.ts';
import { installHomeDataPolicy } from './home-data-policy.ts';
import { installItemAssets } from './item-assets.ts';
import { installLiveLifecycle } from './live-lifecycle.ts';
import { installLoadingStates } from './loading-states.ts';
import { installLeagueFilters } from './major-league-filter.ts';
import { installMatchExperience } from './match-experience.ts';
import { installDotaLivescore } from './dota-livescore.ts';
import { installNativeLifecycle } from './native-lifecycle.ts';
import { installAppUpdater } from './app-updater.ts';
import { installPlayerBoardCopy } from './player-board-copy.ts';
import { installPwaPersistence } from './pwa-persistence.ts';
import { installPwa } from './pwa.ts';
import { currentV3Route, installV3Routing } from './route-page.ts';
import { installScheduleMetadataCapture } from './schedule-metadata.ts';
import { installScoreboardStatus } from './scoreboard-status.ts';
import { installTeamSideIdentity } from './team-side-identity.ts';
import { installWinnerDeclaration } from './winner-declaration.ts';

const root = document.querySelector<HTMLElement>('#app');
if (!root) throw new Error('Missing #app root.');
const dota2Enabled = String(import.meta.env.VITE_ENABLE_DOTA2 ?? '').toLowerCase() === 'true';

installApiReliability();
installHomeDataPolicy(root);
const initialRoute = currentV3Route();
if (initialRoute.kind !== 'match') {
  installCatalogueFinality();
  installCatalogueTeamLogos(root);
  installCatalogueSeriesScores(root);
}
installPwaPersistence();
installLiveLifecycle(root);
installScheduleMetadataCapture();
installFinalSeriesTabs(root);
installNativeLifecycle();
installPlayerBoardCopy(root);
installItemAssets(root);
startWebV2(root);
installScoreboardStatus(root);
installAppUpdater(root);
if (dota2Enabled) installDotaLivescore(root);
installLeagueFilters(root);
installHomeDashboard(root);
installCatalogueExperience(root);
installMatchExperience(root);
installDataStatus(root);
installFinalSnapshotPolling(root);
installV3Routing(root);
installGrubsObjective(root);
installLoadingStates(root);
installArenaBrand(root);
installChampionPortraitAssets(root);
installTeamSideIdentity(root);
installWinnerDeclaration(root);
installPwa();
